export const actionTypes = {
    ADD_RECIPE: "ADD_RECIPE"
}

const is = [
    {id: 0, title: "Chicken Tikka Masala", time: 30, ingredients: ["Chicken", "Garam Masala", "Garlic", "Ginger", "Turmeric", "Coriander", "Cumin", "Yoghurt", "Cardammom", "Chillies", "Heavy Cream"], steps: ["Combine garlic, ginger, turmeric, garam masala, coriander, and cumin in a small bowl. Whisk yogurt, salt, and half of spice mixture in a medium bowl; add chicken and turn to coat. Cover and chill 4-6 hours. Cover and chill remaining spice mixture", "Heat ghee in a large heavy pot over medium heat. Add onion, tomato paste, cardamom, and chiles and cook, stirring often, until tomato paste has darkened and onion is soft, about 5 minutes. Add remaining half of spice mixture and cook, stirring often, until bottom of pot begins to brown, about 4 minutes.", "Add tomatoes with juices, crushing them with your hands as you add them. Bring to a boil, reduce heat, and simmer, stirring often and scraping up browned bits from bottom of pot, until sauce thickens, 8-10 minutes.", "Add cream and chopped cilantro. Simmer, stirring occasionally, until sauce thickens, 30-40 minutes.", "Meanwhile, preheat broiler. Line a rimmed baking sheet with foil and set a wire rack inside sheet. Arrange chicken on rack in a single layer. Broil until chicken starts to blacken in spots (it will not be cooked through), about 10 minutes.", "Cut chicken into bite-size pieces, add to sauce, and simmer, stirring occasionally, until chicken is cooked through, 8-10 minutes. Serve with rice and cilantro sprigs."], imageUrl: "https://cafedelites.com/wp-content/uploads/2018/04/Best-Chicken-Tikka-Masala-IMAGE-1-683x1024.jpg"},
    {id: 1, title: "Butter Chicken", time: 24, ingredients: ["Chicken", "Ginger", "Garlic", "Butter", "Garam Masala"], steps: ["First, mix your yogurt marinade together.", "Marinate chicken for 20 minutes, or overnight if time allows. (The longer it marinates, the more tender your chicken will be.)", "Sear chicken in a skillet or pan. Keep those charred bits on the pan to make your sauce. Browned bits = flavour. If you have too many burnt pieces stuck to the pan, you can discard some of them if you wish.", "Finally, make your curry sauce in the same skillet."], imageUrl: "https://thekitchenpaper.com/wp-content/uploads/2018/01/indian-butter-chicken-recipe-1.jpg"},
    {id: 2, title: "Mashed Potatoes", time: 50, ingredients: ["Potatoes", "Masher"], steps: ["Bring a pot of salted water to a boil. Add potatoes and cook until tender but still firm, about 15 minutes; drain.", "In a small saucepan heat butter and milk over low heat until butter is melted. Using a potato masher or electric beater, slowly blend milk mixture into potatoes until smooth and creamy. Season with salt and pepper to taste."], imageUrl: "https://images-gmi-pmc.edge-generalmills.com/1156f4ec-29c8-4cd9-80db-7d4ee330b1d0.jpg"},
    {id: 3, title: "Pav Bhaji", time: 50, ingredients: ["Pav", "Potatoes", "Peas", "Masher", "Ginger", "Garlic"], steps: ["Select the high Sauté setting on the Instant Pot and heat 2 tablespoons of the butter. Add the yellow onion, ginger, garlic, bell peppers and sauté until the onion turns translucent, about 5 minutes", "Add the cauliflower, potatoes, tomatoes, peas, and 2 teaspoons salt; pour in the water; and stir well with a wooden spoon, nudging loose any browned bits from the pot bottom", "Secure the lid and set the Pressure Release to Sealing. Press the Cancel button, then select the Pressure Cook or Manual setting and set the cooking time for 6 minutes at high pressure", "Perform a quick release by moving the Pressure Release to Venting. Open the pot. Select the normal Sauté setting and mash all the veggies with a potato masher", "Stir in the tomato paste, pav bhaji masala, red chili powder, and turmeric, followed by 2 tablespoons butter (optional but highly recommended). Cover the pot with a glass lid (or other nonlocking lid that fits), as the bhaji may start to splatter, and cook until heated through, about 5 minutes", "Taste and adjust the seasoning with salt, paav bhaji masala, and chile powder if needed. Press the Cancel button to turn off the Instant Pot. Sprinkle with the cilantro"], imageUrl: "https://www.viniscookbook.com/wp-content/uploads/2018/11/20181115_125235.jpg"},
];

export const RecipesReducer = (initialState=is, action) => {
    switch(action.type){
        case actionTypes.ADD_RECIPE:
            return [...initialState, {id: initialState[initialState.length-1].id+1, title: action.payload.title, time: action.payload.time, ingredients: action.payload.ingredients, steps: action.payload.steps, imageUrl: action.payload.imageUrl}]
        default:
            return initialState;
    }
};